--  INACTIVE


-- local function filter_tsserver_diagnostics(_, result, ctx, config)
--   if result.diagnostics == nil then return end
--   -- ignore some tsserver diagnostics
--   local idx = 1
--   while idx <= #result.diagnostics do
--     local entry = result.diagnostics[idx]
--     -- codes: https://github.com/microsoft/TypeScript/blob/main/src/compiler/diagnosticMessages.json
--     -- if entry.source == 
--     --
--
--     --     source = "mypy"
--
--     if entry.code == 80001 then
--       -- { message = "File is a CommonJS module; it may be converted to an ES module.", }
--       table.remove(result.diagnostics, idx)
--     else
--       idx = idx + 1
--     end
--   end
--   vim.lsp.diagnostic.on_publish_diagnostics(_, result, ctx, config)
-- end
