-- | auto_refresh                         | false        | Whether or not `VenvSelect` should automatically refresh its search every time its opened. You can manually refresh it with `Ctrl-r` otherwise.                                                                                                                                                                                                                                                           |
-- | search_venv_managers                 | true         | Whether or not the plugin will look for Venv Manager venvs or skip that search. You can set it to false if you dont use any Venv Managers.                                                                                                                                                                                                                                                                |
-- | search_workspace                     | true         | Whether or not the plugin will look for venvs in the currently active LSP workspace.                                                                                                                                                                                                                                                                                                                      |
-- | path                                 | nil          | A fixed path on the disk where VenvSelect should start its search for venvs. If set, it will use this path instead of the path for the currently opened file in the buffer. It will still go up `parents` number of steps before it searches, so set `parents` option to 0 if you want this specific path to be searched and nothing else. Can be useful if all your projects are in a specific location. |
-- | search                               | true         | This is the Parental Search talked about above. It tries to find venvs in parent paths and below. Use the `parents` option to control how many parents to search.                                                                                                                                                                                                                                         |
-- | dap_enabled                          | false        | When set to true, uses the selected virtual environment with the debugger. Requires extra dependencies to be added to `VenvSelect` dependencies: [nvim-dap-python](https://github.com/mfussenegger/nvim-dap-python), [debugpy](https://github.com/microsoft/debugpy), [nvim-dap](https://github.com/mfussenegger/nvim-dap)                                                                                |
-- | parents                              | 2            | The number of parent directories to go up, before searching all directories below for venvs.                                                                                                                                                                                                                                                                                                              |
-- | name                                 | venv         | The name of the venvs to look for. Can be set to a lua table to search for multiple names (name = {"venv", ".venv"})                                                                                                                                                                                                                                                                                      |
-- | fd_binary_name                       | fd           | `VenvSelect` also tries to find other names for the same program, like `fdfind` and `fd-find` and will use those if found. But you can set something specific here if you need to.                                                                                                                                                                                                                        |
-- | notify_user_on_activate              | true         | `VenvSelect` will notify you with a message when a venv is selected in the user interface.                                                                                                                                                                                                                                                                                                                |
-- | poetry_path                          | [system.lua] | The default path on your system where the plugin looks for Poetry venvs.                                                                                                                                                                                                                                                                                                                                  |
-- | pdm_path                             | [system.lua] | The default path on your system where the plugin looks for PDM venvs.                                                                                                                                                                                                                                                                                                                                     |
-- | pipenv_path                          | [system.lua] | The default path on your system where the plugin looks for Pipenv venvs.                                                                                                                                                                                                                                                                                                                                  |
-- | pyenv_path                           | [system.lua] | The default path on your system where the plugin looks for Pyenv venvs.                                                                                                                                                                                                                                                                                                                                   |
-- | hatch_path                           | [system.lua] | The default path on your system where the plugin looks for Hatch venvs.                                                                                                                                                                                                                                                                                                                                   |
-- | venvwrapper_path                     | [system.lua] | The default path on your system where the plugin looks for VenvWrapper venvs.                                                                                                                                                                                                                                                                                                                             |
-- | anaconda_base_path                   | [system.lua] | The default path on your system where the plugin looks for Anaconda venvs.                                                                                                                                                                                                                                                                                                                                |
-- | anaconda_envs_path                   | [system.lua] | The default path on your system where the plugin looks for Anaconda venvs.                                                                                                                                                                                                                                                                                                                                |
-- | anaconda { python_executable = nil } | 'python' or 'python3' | The name of the anaconda python executable                                                                                                                                                                                                                                                                                                                                                                |
-- | anaconda { python_parent_dir = nil } | 'bin' or 'Scripts'    | The name of the anaconda python parent directory                                                                                                                                                                                                                                                                                                                                                          |

return {
  "linux-cultist/venv-selector.nvim",
  dependencies = { "neovim/nvim-lspconfig", "nvim-telescope/telescope.nvim", "mfussenegger/nvim-dap-python" },
  branch = "regexp",
  config = function(opts, _)
    require("venv-selector").setup {
      name = { ".venv" },
    }
  end,
  ft = { "python" },
  keys = {
    -- Keymap to open VenvSelector to pick a venv.
    { "<leader>vs", "<cmd>VenvSelect<cr>" },
    -- Keymap to retrieve the venv from a cache (the one previously used for the same project directory).
    { "<leader>vc", "<cmd>VenvSelectCached<cr>" },
  },
}
